### ISSUE TITLE
Missing information from readme file !

### ISSUE THREAD

**Issue by jfekete1** [roundonejs/roundonejs#1]
There is no information in the Readme file, how to use this, and in the package.json there is also no start script.
Only "test": "echo \"Error: no test specified\" && exit 1"...

 Error: Can't walk dependency graph: Cannot find module 'D:\MUGEN_JS\roundonejs\third_party\roundonejs_mugen_renderer\src\player.js' from 'D:\MUGEN_JS\roundonejs\third_party\roundonejs_mugen_renderer\src\_fake.js'

How to use this software?

**Comment by carlsonsantana** [comment]
> There is no information in the Readme file, how to use this, and in the package.json there is also no start script.
> Only "test": "echo "Error: no test specified" && exit 1"...

I submit a commit to create a `build` node command, it create a `build` folder with the `roundone.js` file. With this file you use it [like this](https://github.com/roundonejs/roundonejs.github.io/blob/master/js/main.js).

> Error: Can't walk dependency graph: Cannot find module 'D:\MUGEN_JS\roundonejs\third_party\roundonejs_mugen_renderer\src\player.js' from 'D:\MUGEN_JS\roundonejs\third_party\roundonejs_mugen_renderer\src_fake.js'

When I create this library to [encapsulate this other](https://github.com/Tatayecorp/demo_mugenJS), I don't knew that its possible use GitHub projects as dependency, then you need clone the submodules too.
```sh
git clone --recurse-submodules https://github.com/roundonejs/roundonejs.git
```

[You can see this project running here](https://roundonejs.github.io/).

**Comment by carlsonsantana** [comment]
Now I changed the dependency to use Node dependencies.
